/**
 * Problem 2:
 * 
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

#include <iostream>

using namespace std;

int main(void) {
    int sum = 0;

    int a1 = 1;
    int a2 = 2;

    int next;

    while (next < 4000000) {
        next = a1 + a2;
        a1 = a2;
        a2 = next;

        if (next % 2 == 0) {
            sum += next;
        }
    }

    sum += 2;

    cout << sum << endl;
}